# Generated by Django 2.2.2 on 2019-06-17 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_auto_20190616_2312'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.TextField(choices=[('0', 'Telefone Fixo'), ('1', 'Celular 1'), ('2', 'E-Mail')], max_length=1, verbose_name='Tipo Contato')),
                ('kind_text', models.CharField(max_length=15, verbose_name='Conteúdo Tipo')),
                ('whatsapp', models.BooleanField(verbose_name='Whatsapp')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=100, verbose_name='Sobrenome')),
                ('alias', models.CharField(max_length=100, verbose_name='Apelido')),
                ('created_on', models.DateField(auto_now_add=True, verbose_name='Criado em.')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pessoa', to='person.Person')),
            ],
            options={
                'verbose_name': 'Contato da Pessoa',
                'verbose_name_plural': 'Contatos de Pessoas',
                'ordering': ('created_on',),
            },
        ),
    ]
