# Generated by Django 2.2.2 on 2019-06-17 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_personcontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='nascimento',
            field=models.DateField(null=True, verbose_name='Data Nascimento'),
        ),
    ]
